### ISSUE TITLE
Update to VDEM 10

### ISSUE THREAD

**Issue by david-hammond** [xmarquez/vdem#1]
Hi, I have been trying to fork this to update to VDEM 10, I found the ./data-raw/add_vdem_data_and_codebook.Rmd file that reads the new dataset. 

However, after installing the democracyData package, the command on lines 30-38
```
VDem_plus <- VDem_plus %>%
  mutate(country_name = if_else(country_id == 196, "Sao Tome and Principe", country_name)) %>%
  democracyData::country_year_coder(country_name, 
                                    year,
                                    include_in_output = c("extended_country_name", "GWn", "cown", 
                                                        "GW_startdate", "GW_enddate", "GWc", 
                                                        "extended_region","extended_continent", 
                                                        "microstate", "lat", "lon", "in_GW_system"),
                                    match_type = "country")
```
Gives the following 

```Error: Column name `country_name` must not be duplicated.```

Also the pdf_text creates an error too.

I would be happy to fork this and contribute but can't seem to find the sources of these errors.

**Comment by xmarquez** [comment]
Hi David,

Just working on updating to Vdem 10 - can do this next week? There are a
couple of other things that need updating.

**Comment by david-hammond** [comment]
Hi xmarquez, thanks very much, let me know if I can help in anyway

**Comment by xmarquez** [comment]
Hi David, this has now been updated to version 10 of V-Dem. Let me know if
you encounter any issues.

**Comment by david-hammond** [comment]
Thanks xmarquez, just tired it out, looks good, thanks!
